export const COMMON_ERROR_CODES = {
  INVALID_TOKEN: "INVALID_TOKEN",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  MISSING_FIELDS: "MISSING_FIELDS",
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};

export const USR_ERROR_CODES = {
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
};

export const AUTH_ERROR_CODES = {
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
};

export const ROLE_ERROR_CODES = {
  INSUFFICIENT_ROLE: "INSUFFICIENT_ROLE",
  ROLE_NOT_FOUND: "ROLE_NOT_FOUND",
} as const;

export const ERROR_STATUSES = {
  NOT_FOUND: 404,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  BAD_REQUEST: 400,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
} as const;
